import { RudimentItem, RudimentCategory } from '@/types/drum';

export const RUDIMENT_CATEGORIES: {
  id: RudimentCategory;
  name: string;
  label: string;
  color: string;
  badge: string;
  description: string;
}[] = [
  {
    id: 'rolls',
    name: 'Células de Redobles (Rolls)',
    label: 'Rolls',
    color: 'text-cyan-400',
    badge: 'bg-cyan-500/20 text-cyan-300 border-cyan-500/30',
    description: 'Golpes simples, dobles y rulos de rebote múltiple (PAS 1-15).',
  },
  {
    id: 'diddles',
    name: 'Células de Diddles & Paradiddles',
    label: 'Diddles',
    color: 'text-purple-400',
    badge: 'bg-purple-500/20 text-purple-300 border-purple-500/30',
    description: 'Combinaciones sincopadas de golpes simples y dobles (PAS 16-19).',
  },
  {
    id: 'flams',
    name: 'Células de Flam',
    label: 'Flams',
    color: 'text-amber-400',
    badge: 'bg-amber-500/20 text-amber-300 border-amber-500/30',
    description: 'Apoyaturas simples, flamacues y combinaciones avanzadas (PAS 20-30).',
  },
  {
    id: 'drags',
    name: 'Células de Drag',
    label: 'Drags',
    color: 'text-rose-400',
    badge: 'bg-rose-500/20 text-rose-300 border-rose-500/30',
    description: 'Ruffs, apoyaturas dobles, ratamacues y dragadiddles (PAS 31-40).',
  },
  {
    id: 'linear-chops',
    name: 'Híbridos & Linear Chops',
    label: 'Chops & Fills',
    color: 'text-emerald-400',
    badge: 'bg-emerald-500/20 text-emerald-300 border-emerald-500/30',
    description: 'Hertas, combinaciones manos-bombo estilo Gospel, Bonham y Funk lineal.',
  },
  {
    id: 'custom',
    name: 'Mis Rudimentos & Fills',
    label: 'Mis Rudimentos',
    color: 'text-violet-400',
    badge: 'bg-gradient-to-r from-violet-500/20 to-cyan-500/20 text-cyan-300 border-violet-500/40',
    description: 'Rudimentos, patrones y fills personalizados creados por ti.',
  },
];

export const RUDIMENTS_DATA: RudimentItem[] = [
  // ==========================================
  // I. ROLLS (1-15 PAS)
  // ==========================================
  {
    id: 'single-stroke-roll',
    name: 'Single Stroke Roll (PAS 1)',
    category: 'rolls',
    difficulty: 'Principiante',
    description: 'Alternancia pura derecha-izquierda (R-L-R-L). La base de la velocidad y el control.',
    subdivision: 4,
    defaultBpm: 120,
    tags: ['PAS 1', 'Rolls', 'Básico', 'Velocidad', '16ths', 'R L R L'],
    sticking: ['R', 'L', 'R', 'L'],
    steps: [
      { sticking: 'R', accent: true, kitPiece: 'snare' },
      { sticking: 'L', kitPiece: 'snare' },
      { sticking: 'R', kitPiece: 'snare' },
      { sticking: 'L', kitPiece: 'snare' },
    ],
  },
  {
    id: 'single-stroke-four',
    name: 'Single Stroke Four (PAS 2)',
    category: 'rolls',
    difficulty: 'Principiante',
    description: 'Cuatro golpes alternados rápidos con acento resolutivo en el cuarto golpe.',
    subdivision: 4,
    defaultBpm: 120,
    tags: ['PAS 2', 'Rolls', 'Alternado', 'R L R L'],
    sticking: ['R', 'L', 'R', 'L'],
    steps: [
      { sticking: 'R', kitPiece: 'snare' },
      { sticking: 'L', kitPiece: 'snare' },
      { sticking: 'R', kitPiece: 'snare' },
      { sticking: 'L', accent: true, kitPiece: 'crash' },
    ],
  },
  {
    id: 'single-stroke-seven',
    name: 'Single Stroke Seven (PAS 3)',
    category: 'rolls',
    difficulty: 'Intermedio',
    description: 'Siete golpes alternados rápidos finalizando con un acento contundente en el pulso.',
    subdivision: 6,
    defaultBpm: 110,
    tags: ['PAS 3', 'Rolls', 'Sextuplet', 'R L R L R L R'],
    sticking: ['R', 'L', 'R', 'L', 'R', 'L', 'R'],
    steps: [
      { sticking: 'R', kitPiece: 'snare' },
      { sticking: 'L', kitPiece: 'tom1' },
      { sticking: 'R', kitPiece: 'snare' },
      { sticking: 'L', kitPiece: 'tom2' },
      { sticking: 'R', kitPiece: 'snare' },
      { sticking: 'L', kitPiece: 'floorTom' },
      { sticking: 'R', accent: true, kitPiece: 'crash' },
    ],
  },
  {
    id: 'multiple-bounce-roll',
    name: 'Multiple Bounce / Buzz Roll (PAS 4)',
    category: 'rolls',
    difficulty: 'Principiante',
    description: 'Redoble de presión cerrado orquestal con rebotes múltiples sostenidos (Buzz Roll).',
    subdivision: 4,
    defaultBpm: 100,
    tags: ['PAS 4', 'Rolls', 'Buzz', 'Presión', 'Orquestal'],
    sticking: ['R', 'L', 'R', 'L'],
    steps: [
      { sticking: 'R', ghost: true, kitPiece: 'snare' },
      { sticking: 'L', ghost: true, kitPiece: 'snare' },
      { sticking: 'R', ghost: true, kitPiece: 'snare' },
      { sticking: 'L', ghost: true, kitPiece: 'snare' },
    ],
  },
  {
    id: 'triple-stroke-roll',
    name: 'Triple Stroke Roll (PAS 5)',
    category: 'rolls',
    difficulty: 'Intermedio',
    description: 'Tres golpes por mano (R-R-R-L-L-L), comúnmente llamado redoble francés.',
    subdivision: 6,
    defaultBpm: 105,
    tags: ['PAS 5', 'Rolls', 'Triple', 'French', 'R R R L L L'],
    sticking: ['R', 'R', 'R', 'L', 'L', 'L'],
    steps: [
      { sticking: 'R', accent: true, kitPiece: 'snare' },
      { sticking: 'R', kitPiece: 'snare' },
      { sticking: 'R', kitPiece: 'snare' },
      { sticking: 'L', accent: true, kitPiece: 'tom1' },
      { sticking: 'L', kitPiece: 'tom1' },
      { sticking: 'L', kitPiece: 'tom1' },
    ],
  },
  {
    id: 'double-stroke-open-roll',
    name: 'Double Stroke Open Roll (PAS 6)',
    category: 'rolls',
    difficulty: 'Principiante',
    description: 'Did-dles continuos (R-R-L-L). El pilar del control de rebote y técnica Moeller.',
    subdivision: 4,
    defaultBpm: 110,
    tags: ['PAS 6', 'Rolls', 'Double', 'Did-dle', 'R R L L'],
    sticking: ['R', 'R', 'L', 'L'],
    steps: [
      { sticking: 'R', accent: true, kitPiece: 'snare' },
      { sticking: 'R', ghost: true, kitPiece: 'snare' },
      { sticking: 'L', accent: true, kitPiece: 'snare' },
      { sticking: 'L', ghost: true, kitPiece: 'snare' },
    ],
  },
  {
    id: 'five-stroke-roll',
    name: 'Five Stroke Roll (PAS 7)',
    category: 'rolls',
    difficulty: 'Principiante',
    description: 'Dos dobles seguidos de un golpe simple acentuado (R-R-L-L-R).',
    subdivision: 5,
    defaultBpm: 110,
    tags: ['PAS 7', 'Rolls', '5-Stroke', 'R R L L R'],
    sticking: ['R', 'R', 'L', 'L', 'R'],
    steps: [
      { sticking: 'R', kitPiece: 'snare' },
      { sticking: 'R', ghost: true, kitPiece: 'snare' },
      { sticking: 'L', kitPiece: 'snare' },
      { sticking: 'L', ghost: true, kitPiece: 'snare' },
      { sticking: 'R', accent: true, kitPiece: 'crash' },
    ],
  },
  {
    id: 'six-stroke-roll',
    name: 'Six Stroke Roll (PAS 8)',
    category: 'rolls',
    difficulty: 'Intermedio',
    description: 'Acento simple, dos dobles suaves y acento final (R-L-L-R-R-L). Esencial en batería.',
    subdivision: 6,
    defaultBpm: 115,
    tags: ['PAS 8', 'Rolls', '6-Stroke', 'Sextuplet', 'R L L R R L'],
    sticking: ['R', 'L', 'L', 'R', 'R', 'L'],
    steps: [
      { sticking: 'R', accent: true, kitPiece: 'tom1' },
      { sticking: 'L', ghost: true, kitPiece: 'snare' },
      { sticking: 'L', ghost: true, kitPiece: 'snare' },
      { sticking: 'R', ghost: true, kitPiece: 'snare' },
      { sticking: 'R', ghost: true, kitPiece: 'snare' },
      { sticking: 'L', accent: true, kitPiece: 'floorTom' },
    ],
  },
  {
    id: 'seven-stroke-roll',
    name: 'Seven Stroke Roll (PAS 9)',
    category: 'rolls',
    difficulty: 'Intermedio',
    description: 'Tres dobles seguidos de un acento resolutivo (R-R-L-L-R-R-L).',
    subdivision: 7,
    defaultBpm: 100,
    tags: ['PAS 9', 'Rolls', '7-Stroke', 'R R L L R R L'],
    sticking: ['R', 'R', 'L', 'L', 'R', 'R', 'L'],
    steps: [
      { sticking: 'R', kitPiece: 'snare' },
      { sticking: 'R', ghost: true, kitPiece: 'snare' },
      { sticking: 'L', kitPiece: 'snare' },
      { sticking: 'L', ghost: true, kitPiece: 'snare' },
      { sticking: 'R', kitPiece: 'snare' },
      { sticking: 'R', ghost: true, kitPiece: 'snare' },
      { sticking: 'L', accent: true, kitPiece: 'crash' },
    ],
  },
  {
    id: 'nine-stroke-roll',
    name: 'Nine Stroke Roll (PAS 10)',
    category: 'rolls',
    difficulty: 'Intermedio',
    description: 'Cuatro pares de dobles culminando en un golpe acentuado a tierra (R-R-L-L-R-R-L-L-R).',
    subdivision: 4,
    defaultBpm: 105,
    tags: ['PAS 10', 'Rolls', '9-Stroke', '32nds'],
    sticking: ['R', 'R', 'L', 'L', 'R', 'R', 'L', 'L', 'R'],
    steps: [
      { sticking: 'R', kitPiece: 'snare' },
      { sticking: 'R', ghost: true, kitPiece: 'snare' },
      { sticking: 'L', kitPiece: 'snare' },
      { sticking: 'L', ghost: true, kitPiece: 'snare' },
      { sticking: 'R', kitPiece: 'snare' },
      { sticking: 'R', ghost: true, kitPiece: 'snare' },
      { sticking: 'L', kitPiece: 'snare' },
      { sticking: 'L', ghost: true, kitPiece: 'snare' },
      { sticking: 'R', accent: true, kitPiece: 'crash' },
    ],
  },
  {
    id: 'ten-stroke-roll',
    name: 'Ten Stroke Roll (PAS 11)',
    category: 'rolls',
    difficulty: 'Avanzado',
    description: 'Cuatro dobles seguidos de dos notas simples finales (R-R-L-L-R-R-L-L-R-L).',
    subdivision: 5,
    defaultBpm: 100,
    tags: ['PAS 11', 'Rolls', '10-Stroke'],
    sticking: ['R', 'R', 'L', 'L', 'R', 'R', 'L', 'L', 'R', 'L'],
    steps: [
      { sticking: 'R', kitPiece: 'snare' },
      { sticking: 'R', ghost: true, kitPiece: 'snare' },
      { sticking: 'L', kitPiece: 'snare' },
      { sticking: 'L', ghost: true, kitPiece: 'snare' },
      { sticking: 'R', kitPiece: 'snare' },
      { sticking: 'R', ghost: true, kitPiece: 'snare' },
      { sticking: 'L', kitPiece: 'snare' },
      { sticking: 'L', ghost: true, kitPiece: 'snare' },
      { sticking: 'R', accent: true, kitPiece: 'tom1' },
      { sticking: 'L', accent: true, kitPiece: 'floorTom' },
    ],
  },
  {
    id: 'eleven-stroke-roll',
    name: 'Eleven Stroke Roll (PAS 12)',
    category: 'rolls',
    difficulty: 'Intermedio',
    description: 'Cinco dobles con resolución en el undécimo golpe acentuado.',
    subdivision: 6,
    defaultBpm: 95,
    tags: ['PAS 12', 'Rolls', '11-Stroke'],
    sticking: ['R', 'R', 'L', 'L', 'R', 'R', 'L', 'L', 'R', 'R', 'L'],
    steps: [
      { sticking: 'R', kitPiece: 'snare' },
      { sticking: 'R', ghost: true, kitPiece: 'snare' },
      { sticking: 'L', kitPiece: 'snare' },
      { sticking: 'L', ghost: true, kitPiece: 'snare' },
      { sticking: 'R', kitPiece: 'snare' },
      { sticking: 'R', ghost: true, kitPiece: 'snare' },
      { sticking: 'L', kitPiece: 'snare' },
      { sticking: 'L', ghost: true, kitPiece: 'snare' },
      { sticking: 'R', kitPiece: 'snare' },
      { sticking: 'R', ghost: true, kitPiece: 'snare' },
      { sticking: 'L', accent: true, kitPiece: 'crash' },
    ],
  },
  {
    id: 'thirteen-stroke-roll',
    name: 'Thirteen Stroke Roll (PAS 13)',
    category: 'rolls',
    difficulty: 'Avanzado',
    description: 'Seis pares de dobles culminando en golpe de acento simple resolutivo.',
    subdivision: 4,
    defaultBpm: 95,
    tags: ['PAS 13', 'Rolls', '13-Stroke'],
    sticking: ['R', 'R', 'L', 'L', 'R', 'R', 'L', 'L', 'R', 'R', 'L', 'L', 'R'],
    steps: [
      { sticking: 'R', kitPiece: 'snare' },
      { sticking: 'R', ghost: true, kitPiece: 'snare' },
      { sticking: 'L', kitPiece: 'snare' },
      { sticking: 'L', ghost: true, kitPiece: 'snare' },
      { sticking: 'R', kitPiece: 'snare' },
      { sticking: 'R', ghost: true, kitPiece: 'snare' },
      { sticking: 'L', kitPiece: 'snare' },
      { sticking: 'L', ghost: true, kitPiece: 'snare' },
      { sticking: 'R', kitPiece: 'snare' },
      { sticking: 'R', ghost: true, kitPiece: 'snare' },
      { sticking: 'L', kitPiece: 'snare' },
      { sticking: 'L', ghost: true, kitPiece: 'snare' },
      { sticking: 'R', accent: true, kitPiece: 'crash' },
    ],
  },
  {
    id: 'fifteen-stroke-roll',
    name: 'Fifteen Stroke Roll (PAS 14)',
    category: 'rolls',
    difficulty: 'Avanzado',
    description: 'Siete pares de dobles con acento potente en el décimo quinto golpe.',
    subdivision: 8,
    defaultBpm: 90,
    tags: ['PAS 14', 'Rolls', '15-Stroke', '32nds'],
    sticking: ['R', 'R', 'L', 'L', 'R', 'R', 'L', 'L', 'R', 'R', 'L', 'L', 'R', 'R', 'L'],
    steps: [
      { sticking: 'R', kitPiece: 'snare' },
      { sticking: 'R', ghost: true, kitPiece: 'snare' },
      { sticking: 'L', kitPiece: 'snare' },
      { sticking: 'L', ghost: true, kitPiece: 'snare' },
      { sticking: 'R', kitPiece: 'snare' },
      { sticking: 'R', ghost: true, kitPiece: 'snare' },
      { sticking: 'L', kitPiece: 'snare' },
      { sticking: 'L', ghost: true, kitPiece: 'snare' },
      { sticking: 'R', kitPiece: 'snare' },
      { sticking: 'R', ghost: true, kitPiece: 'snare' },
      { sticking: 'L', kitPiece: 'snare' },
      { sticking: 'L', ghost: true, kitPiece: 'snare' },
      { sticking: 'R', kitPiece: 'snare' },
      { sticking: 'R', ghost: true, kitPiece: 'snare' },
      { sticking: 'L', accent: true, kitPiece: 'crash' },
    ],
  },
  {
    id: 'seventeen-stroke-roll',
    name: 'Seventeen Stroke Roll (PAS 15)',
    category: 'rolls',
    difficulty: 'Avanzado',
    description: 'Ocho pares de dobles completando dos tiempos enteros de semicorcheas/fusas.',
    subdivision: 8,
    defaultBpm: 90,
    tags: ['PAS 15', 'Rolls', '17-Stroke'],
    sticking: ['R', 'R', 'L', 'L', 'R', 'R', 'L', 'L', 'R', 'R', 'L', 'L', 'R', 'R', 'L', 'L', 'R'],
    steps: [
      { sticking: 'R', kitPiece: 'snare' },
      { sticking: 'R', ghost: true, kitPiece: 'snare' },
      { sticking: 'L', kitPiece: 'snare' },
      { sticking: 'L', ghost: true, kitPiece: 'snare' },
      { sticking: 'R', kitPiece: 'snare' },
      { sticking: 'R', ghost: true, kitPiece: 'snare' },
      { sticking: 'L', kitPiece: 'snare' },
      { sticking: 'L', ghost: true, kitPiece: 'snare' },
      { sticking: 'R', kitPiece: 'snare' },
      { sticking: 'R', ghost: true, kitPiece: 'snare' },
      { sticking: 'L', kitPiece: 'snare' },
      { sticking: 'L', ghost: true, kitPiece: 'snare' },
      { sticking: 'R', kitPiece: 'snare' },
      { sticking: 'R', ghost: true, kitPiece: 'snare' },
      { sticking: 'L', kitPiece: 'snare' },
      { sticking: 'L', ghost: true, kitPiece: 'snare' },
      { sticking: 'R', accent: true, kitPiece: 'crash' },
    ],
  },

  // ==========================================
  // II. DIDDLES & PARADIDDLES (16-19 PAS)
  // ==========================================
  {
    id: 'single-paradiddle',
    name: 'Single Paradiddle (PAS 16)',
    category: 'diddles',
    difficulty: 'Principiante',
    description: 'El rudimento insignia: golpe alternado seguido de doble (R-L-R-R L-R-L-L).',
    subdivision: 4,
    defaultBpm: 120,
    tags: ['PAS 16', 'Diddles', 'Paradiddle', 'R L R R L R L L', 'Básico'],
    sticking: ['R', 'L', 'R', 'R', 'L', 'R', 'L', 'L'],
    steps: [
      { sticking: 'R', accent: true, kitPiece: 'snare' },
      { sticking: 'L', kitPiece: 'snare' },
      { sticking: 'R', kitPiece: 'snare' },
      { sticking: 'R', ghost: true, kitPiece: 'snare' },
      { sticking: 'L', accent: true, kitPiece: 'tom1' },
      { sticking: 'R', kitPiece: 'snare' },
      { sticking: 'L', kitPiece: 'snare' },
      { sticking: 'L', ghost: true, kitPiece: 'snare' },
    ],
  },
  {
    id: 'double-paradiddle',
    name: 'Double Paradiddle (PAS 17)',
    category: 'diddles',
    difficulty: 'Intermedio',
    description: 'Dos pares simples seguidos de diddle (R-L-R-L-R-R L-R-L-R-L-L) en métrica ternaria/seisillo.',
    subdivision: 6,
    defaultBpm: 110,
    tags: ['PAS 17', 'Diddles', 'Sextuplet', 'R L R L R R'],
    sticking: ['R', 'L', 'R', 'L', 'R', 'R', 'L', 'R', 'L', 'R', 'L', 'L'],
    steps: [
      { sticking: 'R', accent: true, kitPiece: 'ride' },
      { sticking: 'L', kitPiece: 'snare' },
      { sticking: 'R', kitPiece: 'ride' },
      { sticking: 'L', kitPiece: 'snare' },
      { sticking: 'R', kitPiece: 'ride' },
      { sticking: 'R', ghost: true, kitPiece: 'ride' },
      { sticking: 'L', accent: true, kitPiece: 'snare' },
      { sticking: 'R', kitPiece: 'ride' },
      { sticking: 'L', kitPiece: 'snare' },
      { sticking: 'R', kitPiece: 'ride' },
      { sticking: 'L', kitPiece: 'snare' },
      { sticking: 'L', ghost: true, kitPiece: 'snare' },
    ],
  },
  {
    id: 'triple-paradiddle',
    name: 'Triple Paradiddle (PAS 18)',
    category: 'diddles',
    difficulty: 'Intermedio',
    description: 'Tres pares simples seguidos de diddle (R-L-R-L-R-L-R-R L-R-L-R-L-R-L-L).',
    subdivision: 4,
    defaultBpm: 115,
    tags: ['PAS 18', 'Diddles', 'Triple Paradiddle'],
    sticking: ['R', 'L', 'R', 'L', 'R', 'L', 'R', 'R', 'L', 'R', 'L', 'R', 'L', 'R', 'L', 'L'],
    steps: [
      { sticking: 'R', accent: true, kitPiece: 'hihatClosed' },
      { sticking: 'L', kitPiece: 'snare' },
      { sticking: 'R', kitPiece: 'hihatClosed' },
      { sticking: 'L', kitPiece: 'snare' },
      { sticking: 'R', kitPiece: 'hihatClosed' },
      { sticking: 'L', kitPiece: 'snare' },
      { sticking: 'R', kitPiece: 'hihatClosed' },
      { sticking: 'R', ghost: true, kitPiece: 'hihatClosed' },
      { sticking: 'L', accent: true, kitPiece: 'snare' },
      { sticking: 'R', kitPiece: 'hihatClosed' },
      { sticking: 'L', kitPiece: 'snare' },
      { sticking: 'R', kitPiece: 'hihatClosed' },
      { sticking: 'L', kitPiece: 'snare' },
      { sticking: 'R', kitPiece: 'hihatClosed' },
      { sticking: 'L', kitPiece: 'snare' },
      { sticking: 'L', ghost: true, kitPiece: 'snare' },
    ],
  },
  {
    id: 'single-paradiddle-diddle',
    name: 'Single Paradiddle-Diddle (PAS 19)',
    category: 'diddles',
    difficulty: 'Intermedio',
    description: 'Golpe simple seguido de dos dobles consecutivos (R-L-R-R-L-L). Esencial para solos fluidos.',
    subdivision: 6,
    defaultBpm: 120,
    tags: ['PAS 19', 'Diddles', 'Paradiddle-Diddle', 'Sextuplet', 'R L R R L L'],
    sticking: ['R', 'L', 'R', 'R', 'L', 'L'],
    steps: [
      { sticking: 'R', accent: true, kitPiece: 'tom1' },
      { sticking: 'L', kitPiece: 'snare' },
      { sticking: 'R', kitPiece: 'snare' },
      { sticking: 'R', ghost: true, kitPiece: 'snare' },
      { sticking: 'L', kitPiece: 'floorTom' },
      { sticking: 'L', ghost: true, kitPiece: 'floorTom' },
    ],
  },

  // ==========================================
  // III. FLAMS (20-30 PAS)
  // ==========================================
  {
    id: 'flam',
    name: 'Flam (PAS 20)',
    category: 'flams',
    difficulty: 'Principiante',
    description: 'Apoyatura simple: pequeña nota de gracia que precede inmediatamente al golpe principal.',
    subdivision: 2,
    defaultBpm: 100,
    tags: ['PAS 20', 'Flams', 'Apoyatura', 'Grace Note'],
    sticking: ['R', 'L'],
    steps: [
      { sticking: 'R', flam: true, accent: true, kitPiece: 'snare' },
      { sticking: 'L', flam: true, accent: true, kitPiece: 'snare' },
    ],
  },
  {
    id: 'flam-accent',
    name: 'Flam Accent (PAS 21)',
    category: 'flams',
    difficulty: 'Intermedio',
    description: 'Flam en el primer tiempo de un tresillo alternado (lR-L-R rL-R-L). Gran musicalidad.',
    subdivision: 3,
    defaultBpm: 110,
    tags: ['PAS 21', 'Flams', 'Tresillo', 'Triplet'],
    sticking: ['R', 'L', 'R', 'L', 'R', 'L'],
    steps: [
      { sticking: 'R', flam: true, accent: true, kitPiece: 'snare' },
      { sticking: 'L', kitPiece: 'snare' },
      { sticking: 'R', kitPiece: 'snare' },
      { sticking: 'L', flam: true, accent: true, kitPiece: 'tom1' },
      { sticking: 'R', kitPiece: 'snare' },
      { sticking: 'L', kitPiece: 'snare' },
    ],
  },
  {
    id: 'flam-tap',
    name: 'Flam Tap (PAS 22)',
    category: 'flams',
    difficulty: 'Principiante',
    description: 'Flam seguido de un golpe suave con la misma mano (lR-R rL-L).',
    subdivision: 4,
    defaultBpm: 110,
    tags: ['PAS 22', 'Flams', 'Flam Tap', '16ths'],
    sticking: ['R', 'R', 'L', 'L'],
    steps: [
      { sticking: 'R', flam: true, accent: true, kitPiece: 'snare' },
      { sticking: 'R', ghost: true, kitPiece: 'snare' },
      { sticking: 'L', flam: true, accent: true, kitPiece: 'tom1' },
      { sticking: 'L', ghost: true, kitPiece: 'tom1' },
    ],
  },
  {
    id: 'flamacue',
    name: 'Flamacue (PAS 23)',
    category: 'flams',
    difficulty: 'Intermedio',
    description: 'Patrón sincopado único: flam en el 1, fuerte acento en la 2ª semicorchea y flam final.',
    subdivision: 4,
    defaultBpm: 105,
    tags: ['PAS 23', 'Flams', 'Flamacue', 'Síncopa'],
    sticking: ['R', 'L', 'R', 'L', 'R'],
    steps: [
      { sticking: 'R', flam: true, kitPiece: 'snare' },
      { sticking: 'L', accent: true, kitPiece: 'snare' },
      { sticking: 'R', kitPiece: 'snare' },
      { sticking: 'L', kitPiece: 'snare' },
      { sticking: 'R', flam: true, accent: true, kitPiece: 'crash' },
    ],
  },
  {
    id: 'flam-paradiddle',
    name: 'Flam Paradiddle / Flamadiddle (PAS 24)',
    category: 'flams',
    difficulty: 'Intermedio',
    description: 'Single paradiddle con flam en el golpe acentuado inicial (lR-L-R-R rL-R-L-L).',
    subdivision: 4,
    defaultBpm: 110,
    tags: ['PAS 24', 'Flams', 'Flamadiddle', 'Paradiddle'],
    sticking: ['R', 'L', 'R', 'R', 'L', 'R', 'L', 'L'],
    steps: [
      { sticking: 'R', flam: true, accent: true, kitPiece: 'snare' },
      { sticking: 'L', kitPiece: 'snare' },
      { sticking: 'R', kitPiece: 'snare' },
      { sticking: 'R', ghost: true, kitPiece: 'snare' },
      { sticking: 'L', flam: true, accent: true, kitPiece: 'tom1' },
      { sticking: 'R', kitPiece: 'snare' },
      { sticking: 'L', kitPiece: 'snare' },
      { sticking: 'L', ghost: true, kitPiece: 'snare' },
    ],
  },
  {
    id: 'single-flammed-mill',
    name: 'Single Flammed Mill (PAS 25)',
    category: 'flams',
    difficulty: 'Intermedio',
    description: 'Paradiddle invertido (doble-simple-simple) con flam en el downbeat (lR-R-L-R rL-L-R-L).',
    subdivision: 4,
    defaultBpm: 110,
    tags: ['PAS 25', 'Flams', 'Flammed Mill', 'Invertido'],
    sticking: ['R', 'R', 'L', 'R', 'L', 'L', 'R', 'L'],
    steps: [
      { sticking: 'R', flam: true, accent: true, kitPiece: 'snare' },
      { sticking: 'R', ghost: true, kitPiece: 'snare' },
      { sticking: 'L', kitPiece: 'tom1' },
      { sticking: 'R', kitPiece: 'snare' },
      { sticking: 'L', flam: true, accent: true, kitPiece: 'floorTom' },
      { sticking: 'L', ghost: true, kitPiece: 'floorTom' },
      { sticking: 'R', kitPiece: 'snare' },
      { sticking: 'L', kitPiece: 'tom2' },
    ],
  },
  {
    id: 'flam-paradiddle-diddle',
    name: 'Flam Paradiddle-Diddle (PAS 26)',
    category: 'flams',
    difficulty: 'Avanzado',
    description: 'Paradiddle-diddle iniciado con flam acentuado (lR-L-R-R-L-L).',
    subdivision: 6,
    defaultBpm: 115,
    tags: ['PAS 26', 'Flams', 'Sextuplet', 'Diddle'],
    sticking: ['R', 'L', 'R', 'R', 'L', 'L'],
    steps: [
      { sticking: 'R', flam: true, accent: true, kitPiece: 'crash' },
      { sticking: 'L', kitPiece: 'snare' },
      { sticking: 'R', kitPiece: 'tom1' },
      { sticking: 'R', ghost: true, kitPiece: 'tom1' },
      { sticking: 'L', kitPiece: 'floorTom' },
      { sticking: 'L', ghost: true, kitPiece: 'floorTom' },
    ],
  },
  {
    id: 'pataflafla',
    name: 'Pataflafla (PAS 27)',
    category: 'flams',
    difficulty: 'Avanzado',
    description: 'Patrón de 4 semicorcheas con flams en los extremos (lR-L-R-rL). Sonido trotante.',
    subdivision: 4,
    defaultBpm: 100,
    tags: ['PAS 27', 'Flams', 'Pataflafla', 'Trote'],
    sticking: ['R', 'L', 'R', 'L'],
    steps: [
      { sticking: 'R', flam: true, accent: true, kitPiece: 'snare' },
      { sticking: 'L', kitPiece: 'tom1' },
      { sticking: 'R', kitPiece: 'floorTom' },
      { sticking: 'L', flam: true, accent: true, kitPiece: 'snare' },
    ],
  },
  {
    id: 'swiss-army-triplet',
    name: 'Swiss Army Triplet (PAS 28)',
    category: 'flams',
    difficulty: 'Intermedio',
    description: 'Tresillo con flam y mano dominante doblada (lR-R-L lR-R-L). Favorito de marching band y rock.',
    subdivision: 3,
    defaultBpm: 120,
    tags: ['PAS 28', 'Flams', 'Swiss Triplet', 'Tresillo'],
    sticking: ['R', 'R', 'L'],
    steps: [
      { sticking: 'R', flam: true, accent: true, kitPiece: 'snare' },
      { sticking: 'R', kitPiece: 'snare' },
      { sticking: 'L', kitPiece: 'snare' },
    ],
  },
  {
    id: 'inverted-flam-tap',
    name: 'Inverted Flam Tap (PAS 29)',
    category: 'flams',
    difficulty: 'Avanzado',
    description: 'Flam seguido inmediatamente de tap con la mano contraria (lR-L rL-R). Exige gran control.',
    subdivision: 4,
    defaultBpm: 105,
    tags: ['PAS 29', 'Flams', 'Inverted', 'Control'],
    sticking: ['R', 'L', 'L', 'R'],
    steps: [
      { sticking: 'R', flam: true, accent: true, kitPiece: 'snare' },
      { sticking: 'L', ghost: true, kitPiece: 'snare' },
      { sticking: 'L', flam: true, accent: true, kitPiece: 'tom1' },
      { sticking: 'R', ghost: true, kitPiece: 'tom1' },
    ],
  },
  {
    id: 'flam-drag',
    name: 'Flam Drag (PAS 30)',
    category: 'flams',
    difficulty: 'Avanzado',
    description: 'Compuesto de flam seguido de diddle con apoyatura (lR-ll-L rL-rr-R). Alta exigencia técnica.',
    subdivision: 3,
    defaultBpm: 95,
    tags: ['PAS 30', 'Flams', 'Flam Drag', 'Diddle'],
    sticking: ['R', 'L', 'L', 'R', 'L', 'R', 'R', 'L'],
    steps: [
      { sticking: 'R', flam: true, accent: true, kitPiece: 'snare' },
      { sticking: 'L', drag: true, ghost: true, kitPiece: 'snare' },
      { sticking: 'R', accent: true, kitPiece: 'tom1' },
      { sticking: 'L', flam: true, accent: true, kitPiece: 'snare' },
      { sticking: 'R', drag: true, ghost: true, kitPiece: 'snare' },
      { sticking: 'L', accent: true, kitPiece: 'floorTom' },
    ],
  },

  // ==========================================
  // IV. DRAGS & RATAMACUES (31-40 PAS)
  // ==========================================
  {
    id: 'drag',
    name: 'Drag / Ruff (PAS 31)',
    category: 'drags',
    difficulty: 'Principiante',
    description: 'Doble apoyatura suave de notas de gracia (did-dle rápido ll o rr) antes del golpe principal.',
    subdivision: 2,
    defaultBpm: 100,
    tags: ['PAS 31', 'Drags', 'Ruff', 'Apoyatura'],
    sticking: ['R', 'L'],
    steps: [
      { sticking: 'R', drag: true, accent: true, kitPiece: 'snare' },
      { sticking: 'L', drag: true, accent: true, kitPiece: 'snare' },
    ],
  },
  {
    id: 'single-drag-tap',
    name: 'Single Drag Tap (PAS 32)',
    category: 'drags',
    difficulty: 'Intermedio',
    description: 'Drag en la nota de gracia seguido de un tap acentuado alternado (llR-L rrL-R).',
    subdivision: 4,
    defaultBpm: 105,
    tags: ['PAS 32', 'Drags', 'Single Drag Tap'],
    sticking: ['R', 'L', 'L', 'R'],
    steps: [
      { sticking: 'R', drag: true, accent: true, kitPiece: 'snare' },
      { sticking: 'L', kitPiece: 'snare' },
      { sticking: 'L', drag: true, accent: true, kitPiece: 'tom1' },
      { sticking: 'R', kitPiece: 'snare' },
    ],
  },
  {
    id: 'double-drag-tap',
    name: 'Double Drag Tap (PAS 33)',
    category: 'drags',
    difficulty: 'Intermedio',
    description: 'Dos drags en sucesión rápida culminando en un tap resolutivo (llR llR L).',
    subdivision: 3,
    defaultBpm: 100,
    tags: ['PAS 33', 'Drags', 'Double Drag', 'Tresillo'],
    sticking: ['R', 'R', 'L'],
    steps: [
      { sticking: 'R', drag: true, kitPiece: 'snare' },
      { sticking: 'R', drag: true, kitPiece: 'snare' },
      { sticking: 'L', accent: true, kitPiece: 'crash' },
    ],
  },
  {
    id: 'lesson-25',
    name: 'Lesson 25 (PAS 34)',
    category: 'drags',
    difficulty: 'Intermedio',
    description: 'Patrón clásico de marcha: drag seguido de tres golpes simples alternados (llR-L-R-L).',
    subdivision: 4,
    defaultBpm: 110,
    tags: ['PAS 34', 'Drags', 'Lesson 25', 'Marching'],
    sticking: ['R', 'L', 'R', 'L'],
    steps: [
      { sticking: 'R', drag: true, kitPiece: 'snare' },
      { sticking: 'L', kitPiece: 'snare' },
      { sticking: 'R', kitPiece: 'snare' },
      { sticking: 'L', accent: true, kitPiece: 'crash' },
    ],
  },
  {
    id: 'single-dragadiddle',
    name: 'Single Dragadiddle (PAS 35)',
    category: 'drags',
    difficulty: 'Intermedio',
    description: 'Single paradiddle donde el primer golpe se ejecuta con un drag (llR-R-L-R rrL-L-R-L).',
    subdivision: 4,
    defaultBpm: 105,
    tags: ['PAS 35', 'Drags', 'Dragadiddle', 'Paradiddle'],
    sticking: ['R', 'R', 'L', 'R', 'L', 'L', 'R', 'L'],
    steps: [
      { sticking: 'R', drag: true, accent: true, kitPiece: 'snare' },
      { sticking: 'R', ghost: true, kitPiece: 'snare' },
      { sticking: 'L', kitPiece: 'tom1' },
      { sticking: 'R', kitPiece: 'snare' },
      { sticking: 'L', drag: true, accent: true, kitPiece: 'floorTom' },
      { sticking: 'L', ghost: true, kitPiece: 'floorTom' },
      { sticking: 'R', kitPiece: 'snare' },
      { sticking: 'L', kitPiece: 'tom2' },
    ],
  },
  {
    id: 'drag-paradiddle-1',
    name: 'Drag Paradiddle #1 (PAS 36)',
    category: 'drags',
    difficulty: 'Avanzado',
    description: 'Acento simple seguido de drag y paradiddle (R llR-L-R-R L rrL-R-L-L).',
    subdivision: 6,
    defaultBpm: 105,
    tags: ['PAS 36', 'Drags', 'Drag Paradiddle 1'],
    sticking: ['R', 'R', 'L', 'R', 'R', 'L'],
    steps: [
      { sticking: 'R', accent: true, kitPiece: 'snare' },
      { sticking: 'R', drag: true, kitPiece: 'snare' },
      { sticking: 'L', kitPiece: 'tom1' },
      { sticking: 'R', kitPiece: 'snare' },
      { sticking: 'R', ghost: true, kitPiece: 'snare' },
      { sticking: 'L', accent: true, kitPiece: 'floorTom' },
    ],
  },
  {
    id: 'drag-paradiddle-2',
    name: 'Drag Paradiddle #2 (PAS 37)',
    category: 'drags',
    difficulty: 'Avanzado',
    description: 'Acento simple seguido de dos drags y paradiddle completo (R llR llR-L-R-R).',
    subdivision: 6,
    defaultBpm: 95,
    tags: ['PAS 37', 'Drags', 'Drag Paradiddle 2'],
    sticking: ['R', 'R', 'R', 'L', 'R', 'R'],
    steps: [
      { sticking: 'R', accent: true, kitPiece: 'snare' },
      { sticking: 'R', drag: true, kitPiece: 'snare' },
      { sticking: 'R', drag: true, kitPiece: 'snare' },
      { sticking: 'L', kitPiece: 'tom1' },
      { sticking: 'R', kitPiece: 'snare' },
      { sticking: 'R', ghost: true, kitPiece: 'snare' },
    ],
  },
  {
    id: 'single-ratamacue',
    name: 'Single Ratamacue (PAS 38)',
    category: 'drags',
    difficulty: 'Intermedio',
    description: 'Drag en la anacrusa seguido de tresillo y acento final (llR-L-R-L). Clásico del jazz y bandas.',
    subdivision: 4,
    defaultBpm: 110,
    tags: ['PAS 38', 'Drags', 'Single Ratamacue', 'Jazz'],
    sticking: ['R', 'L', 'R', 'L'],
    steps: [
      { sticking: 'R', drag: true, kitPiece: 'snare' },
      { sticking: 'L', kitPiece: 'snare' },
      { sticking: 'R', kitPiece: 'snare' },
      { sticking: 'L', accent: true, kitPiece: 'crash' },
    ],
  },
  {
    id: 'double-ratamacue',
    name: 'Double Ratamacue (PAS 39)',
    category: 'drags',
    difficulty: 'Avanzado',
    description: 'Dos drags en anacrusa seguidos del tresillo y acento resolutivo (llR llR-L-R-L).',
    subdivision: 6,
    defaultBpm: 100,
    tags: ['PAS 39', 'Drags', 'Double Ratamacue'],
    sticking: ['R', 'R', 'L', 'R', 'L'],
    steps: [
      { sticking: 'R', drag: true, kitPiece: 'snare' },
      { sticking: 'R', drag: true, kitPiece: 'snare' },
      { sticking: 'L', kitPiece: 'tom1' },
      { sticking: 'R', kitPiece: 'snare' },
      { sticking: 'L', accent: true, kitPiece: 'crash' },
    ],
  },
  {
    id: 'triple-ratamacue',
    name: 'Triple Ratamacue (PAS 40)',
    category: 'drags',
    difficulty: 'Avanzado',
    description: 'Tres drags sucesivos culminando en el tresillo y acento resolutivo (llR llR llR-L-R-L).',
    subdivision: 8,
    defaultBpm: 95,
    tags: ['PAS 40', 'Drags', 'Triple Ratamacue'],
    sticking: ['R', 'R', 'R', 'L', 'R', 'L'],
    steps: [
      { sticking: 'R', drag: true, kitPiece: 'snare' },
      { sticking: 'R', drag: true, kitPiece: 'snare' },
      { sticking: 'R', drag: true, kitPiece: 'snare' },
      { sticking: 'L', kitPiece: 'tom1' },
      { sticking: 'R', kitPiece: 'snare' },
      { sticking: 'L', accent: true, kitPiece: 'crash' },
    ],
  },

  // ==========================================
  // V. MODERN HYBRIDS & LINEAR CHOPS (41-46)
  // ==========================================
  {
    id: 'herta',
    name: 'Herta (Speed Burst Fill)',
    category: 'linear-chops',
    difficulty: 'Intermedio',
    description: 'Ráfaga de 4 notas rápidas: dos fusas seguidas de dos semicorcheas (R-L-R-L). Clásico de Metal y Gospel.',
    subdivision: 4,
    defaultBpm: 110,
    tags: ['Híbrido', 'Herta', 'Chops', 'Metal', 'Gospel', 'R L R L'],
    sticking: ['R', 'L', 'R', 'L'],
    steps: [
      { sticking: 'R', accent: true, kitPiece: 'snare' },
      { sticking: 'L', kitPiece: 'snare' },
      { sticking: 'R', accent: true, kitPiece: 'tom1' },
      { sticking: 'L', kitPiece: 'floorTom' },
    ],
  },
  {
    id: 'cheese',
    name: 'Cheese (Flam-Drag Compound)',
    category: 'linear-chops',
    difficulty: 'Avanzado',
    description: 'Rudimento híbrido de DCI: flam sobre un diddle cerrado (lRR-L-R-R). Potente ataque.',
    subdivision: 4,
    defaultBpm: 105,
    tags: ['Híbrido', 'DCI', 'Cheese', 'Flam Drag', 'lRR L R R'],
    sticking: ['R', 'L', 'R', 'R'],
    steps: [
      { sticking: 'R', flam: true, drag: true, accent: true, kitPiece: 'snare' },
      { sticking: 'L', kitPiece: 'snare' },
      { sticking: 'R', kitPiece: 'snare' },
      { sticking: 'R', ghost: true, kitPiece: 'snare' },
    ],
  },
  {
    id: 'linear-chop-rlkk',
    name: 'Linear Gospel Chop (R-L-K-K)',
    category: 'linear-chops',
    difficulty: 'Avanzado',
    description: 'El chop lineal de 6 notas más famoso: Caja(R) - Tom(L) - Bombo - Bombo - Caja(R) - Tom(L).',
    subdivision: 6,
    defaultBpm: 115,
    tags: ['Gospel', 'Linear', 'Chops', 'Sextuplet', 'R L K K R L'],
    sticking: ['R', 'L', 'K', 'K', 'R', 'L'],
    steps: [
      { sticking: 'R', accent: true, kitPiece: 'snare' },
      { sticking: 'L', accent: true, kitPiece: 'tom1' },
      { sticking: 'K', accent: true, kitPiece: 'kick' },
      { sticking: 'K', kitPiece: 'kick' },
      { sticking: 'R', accent: true, kitPiece: 'tom2' },
      { sticking: 'L', accent: true, kitPiece: 'floorTom' },
    ],
  },
  {
    id: 'bonham-triplet',
    name: 'Bonham Triplet (R-L-K)',
    category: 'linear-chops',
    difficulty: 'Intermedio',
    description: 'El remate signature de John Bonham (Led Zeppelin): Caja(R) - Floor Tom(L) - Bombo(K) en tresillo pesado.',
    subdivision: 3,
    defaultBpm: 110,
    tags: ['Bonham', 'Rock', 'Triplet', 'Led Zeppelin', 'R L K'],
    sticking: ['R', 'L', 'K'],
    steps: [
      { sticking: 'R', accent: true, kitPiece: 'snare' },
      { sticking: 'L', accent: true, kitPiece: 'floorTom' },
      { sticking: 'K', accent: true, kitPiece: 'kick' },
    ],
  },
  {
    id: 'linear-funk-pocket',
    name: 'Linear 16th Funk Pocket (Tower of Power)',
    category: 'linear-chops',
    difficulty: 'Intermedio',
    description: 'Patrón lineal estilo David Garibaldi: Hi-Hat(R) - Caja Ghost(L) - Bombo(K) - Hi-Hat(R) sin notas superpuestas.',
    subdivision: 4,
    defaultBpm: 100,
    tags: ['Funk', 'Linear', 'Garibaldi', 'Groove', 'Pocket', 'R L K R'],
    sticking: ['R', 'L', 'K', 'R'],
    steps: [
      { sticking: 'R', accent: true, kitPiece: 'hihatClosed' },
      { sticking: 'L', ghost: true, kitPiece: 'snare' },
      { sticking: 'K', accent: true, kitPiece: 'kick' },
      { sticking: 'R', kitPiece: 'hihatClosed' },
    ],
  },
  {
    id: 'chupacabra-hybrid',
    name: 'Chupacabra Hybrid Chop',
    category: 'linear-chops',
    difficulty: 'Avanzado',
    description: 'Híbrido moderno de seisillo combinando flams en toms y dobles en bombo (lR-R-L-L-K-K).',
    subdivision: 6,
    defaultBpm: 110,
    tags: ['Híbrido', 'DCI', 'Chupacabra', 'Double Bass', 'Sextuplet'],
    sticking: ['R', 'R', 'L', 'L', 'K', 'K'],
    steps: [
      { sticking: 'R', flam: true, accent: true, kitPiece: 'tom1' },
      { sticking: 'R', ghost: true, kitPiece: 'tom1' },
      { sticking: 'L', kitPiece: 'floorTom' },
      { sticking: 'L', ghost: true, kitPiece: 'floorTom' },
      { sticking: 'K', accent: true, kitPiece: 'kick' },
      { sticking: 'K', kitPiece: 'kick' },
    ],
  },
];
